import type { Metadata } from "next";
import Link from "next/link";
import Script from "next/script";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdn.jsdelivr.net/npm/beercss@3.11.33/dist/cdn/beer.min.css"
          rel="stylesheet"
        />
        <Script
          src="https://cdn.jsdelivr.net/npm/beercss@3.11.33/dist/cdn/beer.min.js"
          strategy="afterInteractive"
        />
        <Script
          src="https://cdn.jsdelivr.net/npm/material-dynamic-colors@1.1.2/dist/cdn/material-dynamic-colors.min.js"
          strategy="afterInteractive"
        />
      </head>
      <body className={`dark ${geistSans.variable} ${geistMono.variable}`}>
        <nav className="left l">
          <header>
            <nav>
              <Image src="https://www.beercss.com/favicon.png" className="circle extra" alt="BeerCSS favicon" width={32} height={32} />
              <h6>Collink</h6>
            </nav>
          </header>
          <Link href="/">
            <i>home</i>
            <div>Home</div>
          </Link>
          <Link href="/links">
            <i>link</i>
            <div>Links</div>
          </Link>
          <Link href="/collections">
            <i>widgets</i>
            <div>Collections</div>
          </Link>
        </nav>
        <nav className="bottom s">
          <Link href="/">
            <i>home</i>
          </Link>
          <Link href="/links">
            <i>link</i>
          </Link>
          <Link href="/collections">
            <i>widgets</i>
          </Link>
        </nav>
        <main className="responsive" style={{ paddingLeft: 16, paddingRight: 16 }}>
          {children}
        </main>
      </body>
    </html>
  );
}
